exercise_dict_id1 = {
    #OEFENINGSTITLE
    "title": "ademhalingsoefening",
    #OEFENINGSUITLEG
    "B0": "Als je druk of gespannen bent, ben je geneigd steeds hoger te gaan ademhalen.",
    "B1": "Niet lekker onderin je buik, maar hoog op de borst.",
    "B2": "Dat is een oppervlakkige, snellere en onrustigere ademhaling.",#
    "B3": "Door deze ademhalingsoefening kun je spanning wegnemen.",
    "B4": "Ga zo gemakkelijk mogelijk liggen op je rug, en sluit je ogen.",
    #OEFENINGSTEKST
    "C3": "Leg je handen op je buik. Hierdoor kun je straks voelen hoe je buik op en neer gaat.",
    "C4": "Haal diep adem door je neus. Doe dit zonder inspanning.",
    "C5": "Trek je schouders dus niet op en zet je borst niet uit.",
    "C6": "Voel met je handen hoe je buik uitzet bij het inademen.",
    "C7": "Adem daarna via je mond langzaam, hoorbaar uit. …",
    "C8": "Voel met je handen dat je buik weer platter wordt. …",
    "C9": "Zodra je de behoefte voelt, adem je rustig via de neus weer in.",
    "C10": "Voel je buik omhoog komen.",
    "C11": "Adem weer rustig uit, via je mond.",
    "C12": "Voel je je buik weer platter worden?" ,
    "C13": "Herhaal dit een aantal keer terwijl je je concentreert op je ademhaling.",
    "C14": "…",
    "C15": "…",
    "C16": "…",
    "C17": "…",
    "C18": "…",
    "C19": "Laat je ademhaling zo soepel verlopen, dat het een lange stroom van in en uitvloeiende lucht lijkt.",
    "C20": "…",
    "C21": "…",
    "C22": "…",
    "C23": "Als je prettig vindt, kun je in gedachten rustig tellen, terwijl je in- en uitademt.",
    "C24:": "…",
    "C25": "Misschien lukt het niet meteen om onderin je buik adem te halen.",
    "C26": "Dat is niet erg." ,
    "C27": "Probeer het beetje bij beetje.",
    "C28": "Leg je handen steeds iets verder naar beneden op je buik, en breng je ademhaling daar rustig naar toe.",
    "C29": "…",
    "C30": "…",
    "C31": "…"
}

exercise_dict_id2 = {
    #OEFENINGSTITLE
    "title": "Body scan",
    #OEFENINGSUITLEG
    "B0": "Je lichaam geeft signalen af hoe het met je gaat: een bonzend hart als je bang bent of hoofdpijn na een stressvolle dag.",
    "B1": "Ben jij je ervan bewust hoe je lichaam aanvoelt?",
    "B2": "Door middel van deze oefening, de ‘bodyscan’, leer je aandacht te hebben voor je lichaam.",
    "B3": "Dat is het doel: aandacht.",
    "B4": "Het maakt niet uit wát je ervaart.",
    "B5": "Je gedachten zullen tijdens de bodyscan ongetwijfeld afdwalen.",
    "B6": "Dat is heel normaal.",
    "B7": "Merk op waar je aandacht naar afgedwaald was en richt je vervolgens opnieuw op het deel van je lichaam waar je je aandacht op wilde richten.",
    "B8": "Je kunt de oefening zittend of liggend uitvoeren.",
    #OEFENINGSTEKST
    "C0": "Sluit je ogen en breng je aandacht naar je ademhaling.",
    "C1": "Neem waar hoe de lucht langzaam naar binnen gaat door je neus of mond, je longen vult en weer naar buiten gaat.",
    "C2": "…",
    "C3": "…",
    "C4": "…",
    "C5": "Richt nu je aandacht op je buik.",
    "C6": "Merk hoe je buik meebeweegt met de in- en uitademing.",
    "C7": "Neem hiervoor even de tijd.",
    "C8": "…",
    "C9": "…",
    "C10": "…",
    "C11": "Richt je nu op de tenen van je rechtervoet.",
    "C12":"…",
    "C13": "Verplaats je aandacht van je tenen naar je voetzool,",
    "C14": "je hak,",
    "C15": "de bovenkant van je voet,",
    "C16": "je enkel,",
    "C17": "scheenbeen,",
    "C18": "kuit,",
    "C19": "knie en bovenbeen.",
    "C20": "…",
    "C21": "…",
    "C22": "…",
    "C23": "Doe nu hetzelfde bij je linkerbeen.",
    "C24": "Richt je aandacht rustig op je tenen,",
    "C25": "je voetzool",
    "C26": "je hak,",
    "C27": "de bovenkant van je voet,",
    "C28": "je enkel,",
    "C29": "scheenbeen,",
    "C30": "kuit,",
    "C31": "knie en bovenbeen.",
    "C32": "…",
    "C33": "…",
    "C34": "…",
    "C35": "Verplaats nu je aandacht naar je bekken,",
    "C36": "je buik",
    "C37": "en je borst.",
    "C38": "…",
    "C39": "…",
    "C40": "…",
    "C41": "Richt je op je onderrug en de bovenkant van je rug",
    "C42": "…",
    "C43": "…",
    "C44": "…",
    "C45": "Verplaats je aandacht naar je rechterschouder,",
    "C46": "bovenarm,",
    "C47": "onderarm,",
    "C48": "pols,",
    "C49": "hand",
    "C50": "en vingers.",
    "C51": "…",
    "C52": "…",
    "C53": "…",
    "C54": "Doe hetzelfde bij je linkerarm.",
    "C55": "Richt je aandacht op je schouder,",
    "C56": "bovenarm,",
    "C57": "onderarm,",
    "C58": "pols,",
    "C59": "hand",
    "C60": "en vingers.",
    "C61": "…",
    "C62": "…",
    "C63": "…",
    "C64": "Verplaats vervolgens je aandacht naar je nek,",
    "C65": "achterhoofd,",
    "C66": "voorhoofd",
    "C67": "en gezicht.",
    "C68": "Neem waar wat je voelt.",
    "C69": "…",
    "C70": "…",
    "C71": "…",
    "C72": "Wanneer je je hele lichaam op deze manier waargenomen hebt, probeer dan eens om je lichaam als geheel te ervaren in de ruimte waarin je je bevindt.",
    "C73": "…",
    "C74": "…",
    "C75": "…",
    "C76": "Doe vervolgens je ogen weer open neem even de tijd om de ruimte weer in je op te nemen.",
    "C77": "…",
    "C78": "…",
    "C79": "…"
}

exercise_dict_id3 = {
    #OEFENINGSTITLE
    "title": "Mindfulness oefening",
    #OEFENINGSUITLEG
    "B0": "Negatieve gedachten zorgen voor een vervelend of somber gevoel: ‘Het gaat vast niet lukken’ of ‘Ze vonden het vast raar wat ik zei.’",
    "B1": "Je gedachten zijn niet ‘de waarheid’.",
    "B2": "Het zijn slechts gedachten, die komen en gaan.",
    "B3": "Door middel van deze oefening leer je gedachten te zien als voorbijgaande ideeën.",
    #OEFENINGSTEKST
    "C0": "De eerste keer dat je deze oefening doet, kun je er het best even rustig voor gaan zitten.",
    "C1": "Later kun je de oefening makkelijker ‘even tussendoor’ doen.",
    "C2": "Sluit je ogen en richt je aandacht op je gedachten.",
    "C3": "Waar denk je aan?",
    "C4": "Benoem dit hardop.",
    "C5": "…",
    "C6": "…",
    "C7": "…",
    "C8": "Je hoeft helemaal niets met deze gedachte te doen.",
    "C9": "Zie het als een wolkje dat voorbij drijft.",
    "C10": "Lukt het om de gedachte als een wolkje voorbij te laten drijven?",
    "C11": "…",
    "C12": "…",
    "C13": "…",
    "C14": "…",
    "C15": "Als het niet lukt, geeft dat niet.",
    "C16": "Oefening baart kunst.",
    "C17": "Mindfulness draait om aandacht en bewustzijn.",
    "C18": "Dit kun je nooit fout doen.",
    "C19": "Probeer het gerust nog eens.",
    "C20": "…",
    "C21": "…",
    "C22": "…",
    "C23": "…",
    "C24": "Als je merkt dat er weer een gedachtenstroom op gang komt, ga dan weer terug naar deze oefening.",
    "C25": "Focus op iedere nieuwe gedachte en laat die als een wolkje voorbij drijven.",
    "C26": "…",
    "C27": "…",
    "C28": "…"
}
